// 自动生成,请勿手动编辑
// Generated by tools/generate_index.dart

import 'package:flutter/material.dart';
import '../models/category.dart';
import '../models/recipe.dart';

final List<Category> allCategories = [
  Category(
    id: 'home-cooking',
    name: '家常菜',
    icon: Icons.restaurant,
    recipes: [
      Recipe(
        name: '西红柿炒鸡蛋',
        filePath: 'dishes/home-cooking/西红柿炒鸡蛋.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '地三鲜',
        filePath: 'dishes/home-cooking/地三鲜.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '水煮肉片',
        filePath: 'dishes/home-cooking/水煮肉片.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '回锅肉',
        filePath: 'dishes/home-cooking/回锅肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '糖醋里脊',
        filePath: 'dishes/home-cooking/糖醋里脊.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '葱煎豆腐',
        filePath: 'dishes/home-cooking/葱煎豆腐.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '鱼香肉丝',
        filePath: 'dishes/home-cooking/鱼香肉丝.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '茄子炖土豆',
        filePath: 'dishes/home-cooking/茄子炖土豆.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '麻辣香锅',
        filePath: 'dishes/home-cooking/麻辣香锅.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '糖醋鲤鱼',
        filePath: 'dishes/home-cooking/糖醋鲤鱼/糖醋鲤鱼.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '辣椒炒肉',
        filePath: 'dishes/home-cooking/辣椒炒肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '凉拌黄瓜',
        filePath: 'dishes/home-cooking/凉拌黄瓜.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '香干肉丝',
        filePath: 'dishes/home-cooking/香干肉丝.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '香干芹菜炒肉',
        filePath: 'dishes/home-cooking/香干芹菜炒肉/香干芹菜炒肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '清蒸生蚝',
        filePath: 'dishes/home-cooking/清蒸生蚝.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '尖椒炒牛肉',
        filePath: 'dishes/home-cooking/尖椒炒牛肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '小炒肉',
        filePath: 'dishes/home-cooking/小炒肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '洋葱炒猪肉',
        filePath: 'dishes/home-cooking/洋葱炒猪肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '酸辣土豆丝',
        filePath: 'dishes/home-cooking/酸辣土豆丝.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '可乐鸡翅',
        filePath: 'dishes/home-cooking/可乐鸡翅.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '酱牛肉',
        filePath: 'dishes/home-cooking/酱牛肉/酱牛肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '血浆鸭',
        filePath: 'dishes/home-cooking/血浆鸭/血浆鸭.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '清蒸鲈鱼',
        filePath: 'dishes/home-cooking/清蒸鲈鱼/清蒸鲈鱼.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '咕噜肉',
        filePath: 'dishes/home-cooking/咕噜肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '菠菜炒鸡蛋',
        filePath: 'dishes/home-cooking/菠菜炒鸡蛋/菠菜炒鸡蛋.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '水油焖蔬菜',
        filePath: 'dishes/home-cooking/水油焖蔬菜.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '黄瓜炒肉',
        filePath: 'dishes/home-cooking/黄瓜炒肉.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '白灼虾',
        filePath: 'dishes/home-cooking/白灼虾/白灼虾.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '咖喱炒蟹',
        filePath: 'dishes/home-cooking/咖喱炒蟹.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '白菜猪肉炖粉条',
        filePath: 'dishes/home-cooking/白菜猪肉炖粉条.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '冷吃兔',
        filePath: 'dishes/home-cooking/冷吃兔.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '微波炉鸡蛋羹',
        filePath: 'dishes/home-cooking/微波炉鸡蛋羹.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '香菇滑鸡',
        filePath: 'dishes/home-cooking/香菇滑鸡/香菇滑鸡.md',
        category: 'home-cooking',
      ),
      Recipe(
        name: '炒青菜',
        filePath: 'dishes/home-cooking/炒青菜.md',
        category: 'home-cooking',
      ),
    ],
  ),
  Category(
    id: 'breakfast',
    name: '早餐',
    icon: Icons.breakfast_dining,
    recipes: [
      Recipe(
        name: '太阳蛋',
        filePath: 'dishes/breakfast/太阳蛋.md',
        category: 'breakfast',
      ),
      Recipe(
        name: '牛奶燕麦',
        filePath: 'dishes/breakfast/牛奶燕麦.md',
        category: 'breakfast',
      ),
      Recipe(
        name: '果酱吐司',
        filePath: 'dishes/breakfast/吐司果酱.md',
        category: 'breakfast',
      ),
      Recipe(
        name: '溏心蛋',
        filePath: 'dishes/breakfast/溏心蛋.md',
        category: 'breakfast',
      ),
      Recipe(
        name: '水煮玉米',
        filePath: 'dishes/breakfast/水煮玉米.md',
        category: 'breakfast',
      ),
      Recipe(
        name: '微波炉蛋糕',
        filePath: 'dishes/breakfast/微波炉蛋糕.md',
        category: 'breakfast',
      ),
    ],
  ),
  Category(
    id: 'staple',
    name: '主食',
    icon: Icons.rice_bowl,
    recipes: [
      Recipe(
        name: '米饭',
        filePath: 'dishes/staple/米饭.md',
        category: 'staple',
      ),
      Recipe(
        name: '蛋炒饭',
        filePath: 'dishes/staple/蛋炒饭.md',
        category: 'staple',
      ),
      Recipe(
        name: '日式咖喱饭',
        filePath: 'dishes/staple/日式咖喱饭/日式咖喱饭.md',
        category: 'staple',
      ),
      Recipe(
        name: '烙饼',
        filePath: 'dishes/staple/烙饼/烙饼.md',
        category: 'staple',
      ),
      Recipe(
        name: '炒方便面',
        filePath: 'dishes/staple/炒方便面.md',
        category: 'staple',
      ),
      Recipe(
        name: '老干妈拌面',
        filePath: 'dishes/staple/老干妈拌面.md',
        category: 'staple',
      ),
      Recipe(
        name: '醪糟小汤圆',
        filePath: 'dishes/staple/醪糟小汤圆.md',
        category: 'staple',
      ),
      Recipe(
        name: '炒河粉',
        filePath: 'dishes/staple/炒河粉.md',
        category: 'staple',
      ),
      Recipe(
        name: '炸酱面',
        filePath: 'dishes/staple/炸酱面.md',
        category: 'staple',
      ),
      Recipe(
        name: '手工水饺',
        filePath: 'dishes/staple/手工水饺.md',
        category: 'staple',
      ),
      Recipe(
        name: '麻油拌面',
        filePath: 'dishes/staple/麻油拌面.md',
        category: 'staple',
      ),
      Recipe(
        name: '披萨饼皮',
        filePath: 'dishes/staple/pizza/披萨饼皮.md',
        category: 'staple',
      ),
      Recipe(
        name: '热干面',
        filePath: 'dishes/staple/热干面.md',
        category: 'staple',
      ),
      Recipe(
        name: '炒馍',
        filePath: 'dishes/staple/炒馍.md',
        category: 'staple',
      ),
    ],
  ),
  Category(
    id: 'semi-finished',
    name: '半成品加工',
    icon: Icons.kitchen,
    recipes: [
      Recipe(
        name: '速冻汤圆',
        filePath: 'dishes/semi-finished/速冻汤圆/速冻汤圆.md',
        category: 'semi-finished',
      ),
      Recipe(
        name: '速冻水饺',
        filePath: 'dishes/semi-finished/速冻水饺.md',
        category: 'semi-finished',
      ),
      Recipe(
        name: '速冻馄饨',
        filePath: 'dishes/semi-finished/速冻馄饨.md',
        category: 'semi-finished',
      ),
      Recipe(
        name: '凉皮',
        filePath: 'dishes/semi-finished/凉皮.md',
        category: 'semi-finished',
      ),
    ],
  ),
  Category(
    id: 'braised',
    name: '红烧菜系',
    icon: Icons.local_fire_department,
    recipes: [
      Recipe(
        name: '红烧肉',
        filePath: 'dishes/braised/红烧肉/简易红烧肉.md',
        category: 'braised',
      ),
      Recipe(
        name: '南派红烧肉',
        filePath: 'dishes/braised/红烧肉/南派红烧肉.md',
        category: 'braised',
      ),
      Recipe(
        name: '红烧鱼头',
        filePath: 'dishes/braised/红烧鱼头.md',
        category: 'braised',
      ),
      Recipe(
        name: '红烧茄子',
        filePath: 'dishes/braised/红烧茄子.md',
        category: 'braised',
      ),
    ],
  ),
  Category(
    id: 'soup',
    name: '汤与粥',
    icon: Icons.soup_kitchen,
    recipes: [
      Recipe(
        name: '米粥',
        filePath: 'dishes/soup/米粥.md',
        category: 'soup',
      ),
      Recipe(
        name: '皮蛋瘦肉粥',
        filePath: 'dishes/soup/皮蛋瘦肉粥.md',
        category: 'soup',
      ),
      Recipe(
        name: '西红柿鸡蛋汤',
        filePath: 'dishes/soup/西红柿鸡蛋汤.md',
        category: 'soup',
      ),
      Recipe(
        name: '金针菇汤',
        filePath: 'dishes/soup/金针菇汤.md',
        category: 'soup',
      ),
      Recipe(
        name: '罗宋汤',
        filePath: 'dishes/soup/罗宋汤.md',
        category: 'soup',
      ),
      Recipe(
        name: '昂刺鱼豆腐汤',
        filePath: 'dishes/soup/昂刺鱼豆腐汤/昂刺鱼豆腐汤.md',
        category: 'soup',
      ),
      Recipe(
        name: '紫菜蛋花汤',
        filePath: 'dishes/soup/紫菜蛋花汤.md',
        category: 'soup',
      ),
    ],
  ),
  Category(
    id: 'drink',
    name: '饮料',
    icon: Icons.local_drink,
    recipes: [
      Recipe(
        name: '酸梅汁',
        filePath: 'dishes/drink/酸梅汁.md',
        category: 'drink',
      ),
      Recipe(
        name: '百香果橙子特调',
        filePath: 'dishes/drink/百香果橙子特调/百香果橙子特调.md',
        category: 'drink',
      ),
      Recipe(
        name: '杨枝甘露',
        filePath: 'dishes/drink/杨枝甘露.md',
        category: 'drink',
      ),
    ],
  ),
  Category(
    id: 'condiment',
    name: '酱料和其它材料',
    icon: Icons.water_drop,
    recipes: [
      Recipe(
        name: '油泼辣子',
        filePath: 'dishes/condiment/油泼辣子.md',
        category: 'condiment',
      ),
      Recipe(
        name: '蒜香酱油',
        filePath: 'dishes/condiment/蒜香酱油.md',
        category: 'condiment',
      ),
      Recipe(
        name: '糖醋汁',
        filePath: 'dishes/condiment/糖醋汁.md',
        category: 'condiment',
      ),
      Recipe(
        name: '油酥',
        filePath: 'dishes/condiment/油酥.md',
        category: 'condiment',
      ),
      Recipe(
        name: '炒糖色',
        filePath: 'dishes/condiment/糖色.md',
        category: 'condiment',
      ),
    ],
  ),
  Category(
    id: 'dessert',
    name: '甜品',
    icon: Icons.cake,
    recipes: [
      Recipe(
        name: '提拉米苏',
        filePath: 'dishes/dessert/提拉米苏/提拉米苏.md',
        category: 'dessert',
      ),
      Recipe(
        name: '烤蛋挞',
        filePath: 'dishes/dessert/烤蛋挞/烤蛋挞.md',
        category: 'dessert',
      ),
    ],
  ),
];
