import 'dart:io';

void main() {
  print('扫描 README.md...');

  final readmePath = '../HowToCook/README.md';
  final readmeFile = File(readmePath);

  if (!readmeFile.existsSync()) {
    print('错误: 找不到 $readmePath');
    exit(1);
  }

  final readme = readmeFile.readAsStringSync();
  final categories = parseReadme(readme);

  print('发现 ${categories.length} 个分类');
  int totalRecipes = 0;
  for (var cat in categories) {
    totalRecipes += (cat['recipes'] as List).length;
  }
  print('发现 $totalRecipes 个菜谱');

  validateFiles(categories);
  generateIndexFile(categories);
  generateAssetsConfig(categories);

  print('完成！');
}

List<Map<String, dynamic>> parseReadme(String readme) {
  final categories = <Map<String, dynamic>>[];
  final lines = readme.split('\n');

  String? currentCategoryName;
  final recipes = <Map<String, String>>[];

  final iconMap = {
    '家常菜': 'Icons.restaurant',
    '早餐': 'Icons.breakfast_dining',
    '主食': 'Icons.rice_bowl',
    '汤与粥': 'Icons.soup_kitchen',
    '饮料': 'Icons.local_drink',
    '甜品': 'Icons.cake',
    '红烧菜系': 'Icons.local_fire_department',
    '半成品加工': 'Icons.kitchen',
    '酱料和其它材料': 'Icons.water_drop',
  };

  for (var line in lines) {
    if (line.startsWith('### ')) {
      if (currentCategoryName != null && recipes.isNotEmpty) {
        categories.add({
          'id': _toCategoryId(currentCategoryName),
          'name': currentCategoryName,
          'icon': iconMap[currentCategoryName] ?? 'Icons.restaurant',
          'recipes': List.from(recipes),
        });
        recipes.clear();
      }
      currentCategoryName = line.substring(4).trim();
    }

    final recipeMatch = RegExp(r'\* \[(.+?)\]\((.+?)\)').firstMatch(line);
    if (recipeMatch != null && currentCategoryName != null) {
      final name = recipeMatch.group(1)!;
      var path = recipeMatch.group(2)!;
      if (path.startsWith('./')) path = path.substring(2);
      recipes.add({'name': name, 'path': path});
    }
  }

  if (currentCategoryName != null && recipes.isNotEmpty) {
    categories.add({
      'id': _toCategoryId(currentCategoryName),
      'name': currentCategoryName,
      'icon': iconMap[currentCategoryName] ?? 'Icons.restaurant',
      'recipes': List.from(recipes),
    });
  }

  return categories;
}

String _toCategoryId(String name) {
  const idMap = {
    '家常菜': 'home-cooking',
    '早餐': 'breakfast',
    '主食': 'staple',
    '汤与粥': 'soup',
    '饮料': 'drink',
    '甜品': 'dessert',
    '红烧菜系': 'braised',
    '半成品加工': 'semi-finished',
    '酱料和其它材料': 'condiment',
  };
  return idMap[name] ?? name.toLowerCase().replaceAll(' ', '-');
}

void validateFiles(List<Map<String, dynamic>> categories) {
  print('验证文件...');
  var hasErrors = false;

  for (var cat in categories) {
    for (var recipe in cat['recipes'] as List) {
      final mdPath = 'assets/recipes/${recipe['path']}';
      if (!File(mdPath).existsSync()) {
        print('  ✗ 缺失: $mdPath');
        hasErrors = true;
      }
    }
  }

  if (!hasErrors) {
    print('  ✓ 所有 Markdown 文件存在');
  }
}

void generateIndexFile(List<Map<String, dynamic>> categories) {
  final buffer = StringBuffer();
  buffer.writeln('// 自动生成,请勿手动编辑');
  buffer.writeln('// Generated by tools/generate_index.dart');
  buffer.writeln();
  buffer.writeln("import 'package:flutter/material.dart';");
  buffer.writeln("import '../models/category.dart';");
  buffer.writeln("import '../models/recipe.dart';");
  buffer.writeln();
  buffer.writeln('final List<Category> allCategories = [');

  for (var cat in categories) {
    buffer.writeln('  Category(');
    buffer.writeln("    id: '${cat['id']}',");
    buffer.writeln("    name: '${cat['name']}',");
    buffer.writeln("    icon: ${cat['icon']},");
    buffer.writeln('    recipes: [');
    for (var recipe in cat['recipes'] as List) {
      buffer.writeln('      Recipe(');
      buffer.writeln("        name: '${recipe['name']}',");
      buffer.writeln("        filePath: '${recipe['path']}',");
      buffer.writeln("        category: '${cat['id']}',");
      buffer.writeln('      ),');
    }
    buffer.writeln('    ],');
    buffer.writeln('  ),');
  }

  buffer.writeln('];');

  final outputDir = Directory('lib/data');
  if (!outputDir.existsSync()) outputDir.createSync(recursive: true);

  File('lib/data/recipe_index.dart').writeAsStringSync(buffer.toString());
  print('生成 lib/data/recipe_index.dart');
}

void generateAssetsConfig(List<Map<String, dynamic>> categories) {
  final dirs = <String>{'assets/recipes'};

  for (var cat in categories) {
    for (var recipe in cat['recipes'] as List) {
      final path = recipe['path'] as String;
      final dir = path.substring(0, path.lastIndexOf('/'));
      final parts = ('assets/recipes/$dir').split('/');
      for (var i = 2; i <= parts.length; i++) {
        dirs.add(parts.sublist(0, i).join('/'));
      }
    }
  }

  final sortedDirs = dirs.toList()..sort();
  final buffer = StringBuffer();
  buffer.writeln('  assets:');
  for (var dir in sortedDirs) {
    buffer.writeln('    - $dir/');
  }

  File('assets_config.txt').writeAsStringSync(buffer.toString());
  print('生成 assets 配置 -> assets_config.txt');
}
